version: "3.9"
services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_BUCKET=sensor_data
      - INFLUXDB_ORG=arduino
      - INFLUXDB_TOKEN=token123 # generate your token
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data:
