#pragma once

#define DHT_PIN 7
#define DHT_TYPE DHT22
#define EXH_FAN_INTERRUPT_PIN 2
#define EXH_FAN_CONTROL_PIN 9
#define ALARM_LIGHT_PIN 4
#define HUMIDIFIER_PIN 8
#define WATER_PUMP_PIN 12
#define POWER_SWITCH_PIN 13
#define SOIL_MOISTURE_PIN A0
